# -*- coding: utf-8 -*-
"""streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ATuf9sAMK99g7BwZ2ciW6-aeeBASNnNh
"""

pip install streamlit

import streamlit as st

st.title("Hello Samyutha !")
st.subheader("This is my first Streamlit app")
st.write("Welcome to Streamlit 🚀 It's super easy to build apps!")